  on:
    push:
      branches:
        - main
      tags:
        - RC.*

    # This workflow_dispatch allows
    # you to trigger the workflow manually.  
    workflow_dispatch:
      inputs:
        buildConfiguration:
          type: choice
          default: Release
          description: Choose a holder
          options:
            - Debug
            - Release
            - AAPharmaDEV
            - AAPharmaProd
            - AAPharmaDEMO
            - AAPharmaVAL
            - GSIRProd
            - GSIRDev
            - GSIRVal
            - AAPharmaDev
            - MMMPharmaVal
            - MMMPharmaProd
            - MMMPharmaDev
            - MMMPharmaDemo
            - AAPharmaDemo
            - IndiviorDev
            - IndiviorVal
            - ReportumDev
            - ReportumProd
            - ReportumVal
            - BayerDev
            - BayerProd
            - BayerVal
          required: true

  jobs:
    build:
      runs-on: macos-12
      steps:
        - name: setup-xamarin
          uses: maxim-lobanov/setup-xamarin@v1.2
          with:
            mono-version: latest # specify version in '<major>.<minor>' format
            xamarin-ios-version: latest # specify version in '<major>' format
            xamarin-mac-version: latest # specify 'latest' keyword to pick up the latest available version
            xamarin-android-version: latest # specify full version; it is not recomended option because your pipeline can be broken suddenly in future
            xcode-version: '14.x' # set the latest available Xcode 11

        - name: Checkout
          uses: actions/checkout@v2

        - name: Setup iOS Certificates
          uses: apple-actions/import-codesign-certs@v1
          with:
            p12-file-base64: ${{ secrets.CERTIFICATES_P12 }}
            p12-password: ${{ secrets.CERTIFICATES_P12_PASSWORD }}
            keychain: github-actions-xamarin
            keychain-password: ''

        - name: Setup iOS Provisioning Profiles
          uses: apple-actions/download-provisioning-profiles@v1
          with:
            bundle-id: 'com.mymedsandme.*'
            issuer-id: ${{ secrets.APPSTORE_ISSUER_ID }}
            api-key-id: ${{ secrets.APPSTORE_KEY_ID }}
            api-private-key: ${{ secrets.APPSTORE_PRIVATE_KEY }}

        - name: Restore NuGet packages
          run: nuget restore

        - name: Build iOS
          run: MSBuild
            /t:Build
            /p:Configuration=Release
            /p:Platform=iPhone
            /p:BuildIpa=true
            ./TestGithubActions.iOS/TestGithubActions.iOS.csproj

        - name: Setup .NET
          uses: actions/setup-dotnet@v1
          with:
            dotnet-version: 3.x

        - name: Restore dependencies
          run: dotnet restore Release

        - name: Build
          run: dotnet build Release

        - name: Test
          run: dotnet test Release --logger "trx;LogFileName=test-results.trx" || true

        - name: 'Upload app to TestFlight'
          uses: apple-actions/upload-testflight-build@v1
          with:
            app-path: './TestGithubActions.iOS/bin/iPhone/Release/TestGithubActions.iOS.ipa'
            issuer-id: ${{ secrets.APPSTORE_ISSUER_ID }}
            api-key-id: ${{ secrets.APPSTORE_KEY_ID }}
            api-private-key: ${{ secrets.APPSTORE_PRIVATE_KEY }}
