  on:
    # This workflow_dispatch allows
    # you to trigger the workflow manually.  
    workflow_dispatch:
      inputs:
        version:
          description: new app version x.x.x.
        buildConfiguration:
          type: choice
          default: Release
          description: Choose a holder
          options:
            - TestNewConfig
            - Release
          required: true

  jobs:
    Tests:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: Run Unit Tests
          run: dotnet test TestProject1.Test -v n

    Build:
      runs-on: macos-12
      needs: Tests
      steps:
        - name: setup-xamarin
          uses: maxim-lobanov/setup-xamarin@v1.2
          with:
            mono-version: '6.12.0.188'
            xamarin-ios-version: '16.0.0.72'
            xamarin-mac-version: '8.12.0.2'
            xamarin-android-version: '13.1.0.1'
            xcode-version: '14.1'

        - name: Checkout
          uses: actions/checkout@v3

        - name: Setup iOS Certificates
          uses: apple-actions/import-codesign-certs@v1
          with:
            p12-file-base64: ${{ secrets.CERTIFICATES_P12 }}
            p12-password: ${{ secrets.CERTIFICATES_P12_PASSWORD }}
            keychain: github-actions-xamarin
            keychain-password: ''
            
        - uses: dkershner6/switch-case-action@v1
          id: switch-case-bundle
          with:
            default: "Default bundle"
            conditionals-with-values: |
              ${{ github.event.inputs.buildConfiguration == 'Release' }} => com.mymedsandme.*
              ${{ github.event.inputs.buildConfiguration == 'TestNewConfig' }} => 'com.reportum.safetrack-dev'

        - run: echo ${{ steps.switch-case-bundle.outputs.value }}
        
        - name: Setup iOS Provisioning Profiles
          uses: apple-actions/download-provisioning-profiles@v1
          with:
            bundle-id: '${{ steps.switch-case-bundle.outputs.value }}'
            issuer-id: ${{ secrets.APPSTORE_ISSUER_ID }}
            api-key-id: ${{ secrets.APPSTORE_KEY_ID }}
            api-private-key: ${{ secrets.APPSTORE_PRIVATE_KEY }}
          
        - name: Update iOS version Info.plist
          uses: damienaicheh/update-ios-version-info-plist-action@v1.1.0
          with:
            info-plist-path: './TestGithubActions.iOS/Info.plist'
            bundle-short-version-string: '${{ github.event.inputs.version }}"'
            bundle-version: '${{ github.event.inputs.version }}.${{github.run_number}}'
            print-file: true

        - name: Restore NuGet packages
          run: nuget restore

        - name: Build iOS
          run: MSBuild
            /t:Build
            /p:Configuration=${{ github.event.inputs.buildConfiguration }}
            /p:Platform=iPhone
            /p:BuildIpa=true
            ./TestGithubActions.iOS/TestGithubActions.iOS.csproj

        - name: Upload build artifacts
          uses: actions/upload-artifact@v2
          with:
            name: iOS Artifacts
            path: './TestGithubActions.iOS/bin/iPhone/${{ github.event.inputs.buildConfiguration }}/TestGithubActions.iOS.ipa'

        - name: 'Upload app to TestFlight'
          uses: apple-actions/upload-testflight-build@v1
          with:
            app-path: './TestGithubActions.iOS/bin/iPhone/${{ github.event.inputs.buildConfiguration }}/TestGithubActions.iOS.ipa'
            issuer-id: ${{ secrets.APPSTORE_ISSUER_ID }}
            api-key-id: ${{ secrets.APPSTORE_KEY_ID }}
            api-private-key: ${{ secrets.APPSTORE_PRIVATE_KEY }}

    Create_Tag:
      runs-on: ubuntu-latest
      needs: Tests
      steps:
        - uses: actions/checkout@v3

        - name: Create tag
          uses: rickstaa/action-create-tag@v1.5.0
          with:
            tag: '${{ github.event.inputs.buildConfiguration }} ${{ github.event.inputs.version }}.${{github.run_number}}'