  on:
    # This workflow_dispatch allows
    # you to trigger the workflow manually.  
    workflow_dispatch:
      inputs:
        version:
          description: new app version x.x.x.
        buildConfiguration:
          type: choice
          default: Release
          description: Choose a holder
          options:
            - Debug
            - Release
            - AAPharmaDEV
            - AAPharmaProd
            - AAPharmaDEMO
            - AAPharmaVAL
            - GSIRProd
            - GSIRDev
            - GSIRVal
            - AAPharmaDev
            - MMMPharmaVal
            - MMMPharmaProd
            - MMMPharmaDev
            - MMMPharmaDemo
            - AAPharmaDemo
            - IndiviorDev
            - IndiviorVal
            - ReportumDev
            - ReportumProd
            - ReportumVal
            - BayerDev
            - BayerProd
            - BayerVal
          required: true

  jobs:
    Tests:

      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v3

        - name: Run Unit Tests
          run: dotnet test TestProject1 -v n

    build:
      runs-on: macos-12
      steps:
        - name: setup-xamarin
          uses: maxim-lobanov/setup-xamarin@v1.2
          with:
            mono-version: latest # specify version in '<major>.<minor>' format
            xamarin-ios-version: latest # specify version in '<major>' format
            xamarin-mac-version: latest # specify 'latest' keyword to pick up the latest available version
            xamarin-android-version: latest # specify full version; it is not recomended option because your pipeline can be broken suddenly in future
            xcode-version: '14.x' # set the latest available Xcode 11

        - name: Checkout
          uses: actions/checkout@v3

        - name: Setup iOS Certificates
          uses: apple-actions/import-codesign-certs@v1
          with:
            p12-file-base64: ${{ secrets.CERTIFICATES_P12 }}
            p12-password: ${{ secrets.CERTIFICATES_P12_PASSWORD }}
            keychain: github-actions-xamarin
            keychain-password: ''

        - name: Setup iOS Provisioning Profiles
          uses: apple-actions/download-provisioning-profiles@v1
          with:
            bundle-id: 'com.mymedsandme.*'
            issuer-id: ${{ secrets.APPSTORE_ISSUER_ID }}
            api-key-id: ${{ secrets.APPSTORE_KEY_ID }}
            api-private-key: ${{ secrets.APPSTORE_PRIVATE_KEY }}
            
        - name: Set iOS version
          run: |
            /usr/libexec/PlistBuddy -c "Set :CFBundleShortVersionString ${{ github.event.inputs.version }}" ./GitHubActions.iOS/Info.plist
            /usr/libexec/PlistBuddy -c "Set :CFBundleVersion ${{ github.event.inputs.version }}.${{github.run_number}}" ./GitHubActions.iOS/Info.plist

        - name: Restore NuGet packages
          run: nuget restore

        - name: Build iOS
          run: MSBuild
            /t:Build
            /p:Configuration=${{ github.event.inputs.buildConfiguration }}
            /p:Platform=iPhone
            /p:BuildIpa=true
            ./TestGithubActions.iOS/TestGithubActions.iOS.csproj

        - name: Upload build artifacts
          uses: actions/upload-artifact@v2
          with:
            name: iOS Artifacts
            path: './TestGithubActions.iOS/bin/iPhone/${{ github.event.inputs.buildConfiguration }}/TestGithubActions.iOS.ipa'

        - name: 'Upload app to TestFlight'
          uses: apple-actions/upload-testflight-build@v1
          with:
            app-path: './TestGithubActions.iOS/bin/iPhone/${{ github.event.inputs.buildConfiguration }}/TestGithubActions.iOS.ipa'
            issuer-id: ${{ secrets.APPSTORE_ISSUER_ID }}
            api-key-id: ${{ secrets.APPSTORE_KEY_ID }}
            api-private-key: ${{ secrets.APPSTORE_PRIVATE_KEY }}
